### ISSUE TITLE
Backend in 4.1.2 (JS files)

### ISSUE THREAD

**Issue by dassaffe** [contao-components/contao#3] opened 2016-04-07 08:28 UTC
After updating (or more like replacing the fixed files from #2 ), I still get some JS errors

Seems to be mootools (1.5.1)-related ?

ReferenceError: Tips is not defined
...ent,e)}}),Request.Mixed=Request.Contao,Tips.Contao=new Class({Extends:Tips,optio...

ReferenceError: Locale is not defined

Couldn't figure out what raises this error :/

**Comment by leofeyer** [comment] 2016-04-07 12:02
Does the error occur in the online demo? The JS files are almost identical in Contao 3.5 and 4.1.

**Comment by dassaffe** [comment] 2016-04-07 12:17
No, doesn't affect the online-demo. I Havn't upgraded the system though. I fresh installed a 4.1.2 via composoer. 
This results in not having "footer"-bar in the media-manager (for example). I can't "apply" if I want to change an image. 
![rs1](https://cloud.githubusercontent.com/assets/10391350/14350758/8228e84e-fccb-11e5-88ed-39ceaa85c8bb.png)
![rs2](https://cloud.githubusercontent.com/assets/10391350/14350759/82291fd0-fccb-11e5-860c-6777c25bf23a.png)

**Comment by fritzmg** [comment] 2016-04-07 17:02
Which command did you use to install Contao 4 via composer? Did you use
```
php composer.phar create-project contao/standard-edition <target>
```
? Just to check if there is any difference.

**Comment by dassaffe** [comment] 2016-04-07 17:49
I think it was this:
`php composer.phar create-project contao/standard-edition <target> ~4.1.2`

**Comment by leofeyer** [comment] 2016-04-08 19:00
Did you purge the script cache? Which package versions have been installed?

**Comment by champagnierle** [comment] 2016-04-09 06:22
Hi,
I installed 4.1.2 two days ago. And it is not possible to work in the BE like in the 3.5. 
Mistake following the console: "AjaxRequest is not defined"
thouch in the assets I find the "mootools" js defining a variable AjaxRequest - but this "var AjaxRequest=" disappers twice in the js. Is this correct?
P.S. I rebuilt the script cache before posting. Installed version of contao-core is 4.1.2, of contao 4.1.0

**Comment by fritzmg** [comment] 2016-04-09 08:15
> thouch in the assets I find the "mootools" js defining a variable AjaxRequest - but this "var AjaxRequest=" disappers twice in the js. Is this correct?

See contao-components/contao#2 - the `core.min.js` file is currently broken and there is no new release yet unfortunately. You have to update/fix the file yourself.

**Comment by leofeyer** [comment] 2016-04-10 18:48
That's why I was asking about the package versions, which have been installed. The issue should be fixed in version 4.2.3 of the `contao-components/contao` package.

**Comment by fritzmg** [comment] 2016-04-11 07:49
> That's why I was asking about the package versions, which have been installed. The issue should be fixed in version 4.2.3 of the contao-components/contao package.

When doing `php composer.phar create-project contao/standard-edition <target>` it installs `contao-components/contao` `4.2.2` for some reason, instead of `4.2.3`. When doing a `composer update` afterwards, it will updte from `4.2.2` to `4.2.3`.

**Comment by leofeyer** [comment] 2016-04-11 07:51
True, `create-project` will execute `composer install`, which reads the `composer.lock` file. 😞

**Comment by leofeyer** [comment] 2016-04-11 07:51
@dassaffe Can you please run `composer udpate` and check if it fixes the problem?

**Comment by fritzmg** [comment] 2016-04-11 08:01
> True, create-project will execute composer install, which reads the composer.lock file. :disappointed:

Oh I see. Maybe it's better to change the `composer.json` of `contao/standard-edition`, so that it only requires specific versions of the contao components etc. and change the `build.xml` to use `update` instead of `install`?  Not sure if this has other undesired effects.

**Comment by dassaffe** [comment] 2016-04-11 12:04
I ran the update, but it didn't change anything :/ still the same problem. I cleared the cache via composer clear-cache. :(

**Comment by leofeyer** [comment] 2016-04-15 10:39
The correct version has been installed now. Please purge the script cache in the maintenance module or using the `app/console contao:automator` command.

**Comment by dassaffe** [comment] 2016-04-15 11:46
Tried it, but still the same error-message :'( - Purged the script-cache with the automator. Will try to install another instance soon and give feedback, if this problem still exists

**Comment by leofeyer** [comment] 2016-04-21 12:18
I cannot reproduce the issue here.

**Closed by leofeyer** 2016-04-21 12:18 UTC
